### ISSUE TITLE
Says syncing, but highest block not increasing

### ISSUE THREAD

**Issue by willwillis** [Mrlafontaine/Unraid-ErgoNode#1]
I don't know if this is due to the v5 upgrade or what, but I upgraded yesterday, and the highest block size hasn't increased since then. How can I check to see what's going on?

![image](https://user-images.githubusercontent.com/46991/205979992-40b4c4fd-3a19-4d30-a261-5a4a744988fb.png)

Could this be a discrepancy between the UI and back-end? In the attached log, I see references to `890371` in the logs, which is consistent with the block height on https://explorer.ergoplatform.com/

[ergo-logs.txt](https://github.com/Mrlafontaine/Unraid-ErgoNode/files/10168796/ergo-logs.txt)

Thanks.

**Comment by JulienPlomteux** [comment]
Update to 5.0.4, I think there might be a bug in 5.0.3

**Comment by JulienPlomteux** [comment]
but block 844672 seems to be the hardfork block for eip37.. try downgrading the node to version v4.0.103 just to pass the block
![image](https://user-images.githubusercontent.com/60188215/205989168-9ea13e1a-af92-416e-ac84-fa57c8f1821c.png)

**Comment by willwillis** [comment]
Good idea. the node may have been offline for a bit without me realizing it. I've downgraded to `ergoplatform/ergo:v4.0.103` and while I don't see any changes _yet_, I'll check on it in a few hours. 

I really appreciate the help :+1:

**Comment by willwillis** [comment]
Downgrading didn't seem to help, and neither did anything from this troubleshooting resource https://docs.ergoplatform.com/node/install/troubleshooting/#lowering-maxconnections

In the Ergo support Discord I saw others with tx issues around this same height, and the suggestion was to re-synch.
